apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: orleans-demo
data:
  APPLICATIONINSIGHTS_CONNECTION_STRING: $APPLICATIONINSIGHTS_CONNECTION_STRING
  AZURE_STORAGE_NAME: $AZURE_STORAGE_NAME
  MANAGEDIDENTITY_CLIENTID: $MANAGEDIDENTITY_CLIENTID