apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-silo
  namespace: orleans-demo
  labels:
    app: booking-silo
spec:
  selector:
    matchLabels:
      app: booking-silo
  replicas: 2
  template:
    metadata:
      labels:
        app: booking-silo

        # The serviceId label is used to identify the service to Orleans
        orleans/serviceId: booking-silo

        # The clusterId label is used to identify an instance of a cluster to Orleans.
        # Typically, this will be the same value as serviceId or any fixed value.
        # In cases where you are not using rolling deployments (for example, blue/green deployments),
        # this value can allow for distinct clusters which do not communicate directly with each others,
        # but which still share the same storage and other resources.
        orleans/clusterId: booking

        # Workload identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: orleans-demo-sa
      containers:
        - name: main
          image: mbaksacr.azurecr.io/booking.silo:$BOOKERIZER_VERSION
          ports:
          - containerPort: 11111
          - containerPort: 30000
          - containerPort: 80
          env:
          # Configure settings to let Orleans know which cluster it belongs to and which pod it is running in
          - name: ORLEANS_SERVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: booking-config
                key: APPLICATIONINSIGHTS_CONNECTION_STRING
          - name: AZURE_STORAGE_NAME
            valueFrom:
              configMapKeyRef:
                name: booking-config
                key: AZURE_STORAGE_NAME
          - name: MANAGEDIDENTITY_CLIENTID
            valueFrom:
              configMapKeyRef:
                name: booking-config
                key: MANAGEDIDENTITY_CLIENTID
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://tracelens-collector.orleans-demo.svc.cluster.local:4317
      terminationGracePeriodSeconds: 180
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: booking-scaler
  namespace: orleans-demo
spec:
  scaleTargetRef:
    name: booking-silo
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 5
  triggers:
  - type: external
    metadata:
      scalerAddress: booking-scaler.orleans-demo.svc.cluster.local:80
      graintype: 'timeslot'
      upperbound: '300'
---
apiVersion: v1
kind: Service
metadata:
  name: booking-silo
  namespace: orleans-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: booking-silo