apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # This is the ClientId of the user assigned managed identity we want to use
    azure.workload.identity/client-id: "$MANAGEDIDENTITY_CLIENTID"
  labels:
    azure.workload.identity/use: "true"
  name: orleans-demo-sa
  namespace: orleans-demo